In [3]:
import pandas as pd

In [23]:
pew =  pd.read_csv('C:/Users/Hp/Downloads/pew.csv')
pew.head()

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
0,Agnostic,27,34,60,81,76,137,122,109,84,96
1,Atheist,12,27,37,52,35,70,73,59,74,76
2,Buddhist,27,21,30,34,33,58,62,39,53,54
3,Catholic,418,617,732,670,638,1116,949,792,633,1489
4,Don’t know/refused,15,14,15,11,10,35,21,17,18,116

In [29]:
pew.melt(value_vars='religion')

    variable                    value
0   religion                 Agnostic
1   religion                  Atheist
2   religion                 Buddhist
3   religion                 Catholic
4   religion       Don’t know/refused
5   religion         Evangelical Prot
6   religion                    Hindu
7   religion  Historically Black Prot
8   religion        Jehovah's Witness
9   religion                   Jewish
10  religion            Mainline Prot
11  religion                   Mormon
12  religion                   Muslim
13  religion                 Orthodox
14  religion          Other Christian
15  religion             Other Faiths
16  religion    Other World Religions
17  religion             Unaffiliated